name: thirtysix_pics
description: A minimalist photo app with 36-shot limit
version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.3.1
  camera: ^0.10.5+2
  path_provider: ^2.1.2
  gallery_saver: ^2.3.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/mock_viewfinder.jpg
    - assets/fonts/
    - assets/overlays/crosshair.webp

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
    - family: Courier Prime
      fonts:
        - asset: assets/fonts/CourierPrime-Regular.ttf
    